version: '3'
services:
  web:
    image: docker-registry.tools.wmflabs.org/toollabs-php-web
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    ports:
      - 8888:80
    command:
      - ./var/www/bin/start
    volumes:
      - ./etc/lighttpd/lighttpd.conf:/etc/lighttpd/lighttpd.conf:cached
      - ./:/var/www:cached
    links:
      - enwiki.db-replica
  watch:
    image: docker-registry.tools.wmflabs.org/toollabs-nodejs-web
    working_dir: /code/client/
    command:
      - ./bin/watch
    volumes:
      - ./:/code:cached
  enwiki.db-replica:
    build:
      context: .
      dockerfile: Dockerfile-replica-db
    env_file:
      - ./server/.env
    ports:
      - 4711:4711
